### ISSUE TITLE
Non eip155 chains can no longer connect on react-wallet-v2

### ISSUE THREAD

**Issue by radumojic** [WalletConnect/web-examples#166]
The web examples for non eip155 connections stopped working

How to reproduce:
- From https://react-app.walletconnect.com/ initiate a connection with a non eip155 chain ( Solana, Polkadot, Elrond, NEAR, Tron or Tezos )
- On https://react-wallet.walletconnect.com/walletconnect you are not able to select an address and approve the connection on those chainIds.

<img width="230" alt="Screenshot 2023-05-24 at 13 30 53" src="https://github.com/WalletConnect/web-examples/assets/74196626/69f8e01d-f62a-4edb-9fbc-01cb037cd161">

In the #164 PR, non eip155 addresses were removed ( probably by mistake )from react-wallet-v2, making it impossible to connect the example wallet to the example dapp on other chains

changes here: https://github.com/WalletConnect/web-examples/pull/164/commits/a5263fb38118b066b8f13e74e2c364c269bc2bf3#diff-13c2fcb20328b7dd8c859805fae6cf5d7221155c663b05dda87362297567706aL112

**Comment by bkrem** [comment]
Closing, fixed via #167
