### ISSUE TITLE
fix: React Wallet cannot handle simultaneous Sign Requests

### ISSUE THREAD

**Issue by arein** [WalletConnect/web-examples#174]
Repro Steps:
1. Connect to 2 dapps e.g. lab.web3modal.com and react-app.walletconnect.com with react-wallet.walletconnect.com
2. Click sign on both of them
3. Approve in react wallet

Expected behavior:
I can sign them one after the other

Actual behavior:
I can only sign the first one

**Comment by ganchoradkov** [comment]
Closing as this functionality is now integrated into `sign-client`SDK
