### ISSUE TITLE
Examples broken

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/web-examples#217]
- react-dapp-v2-with-ethers
- react-dapp-v2-with-web3js

<img width="984" alt="image" src="https://github.com/WalletConnect/web-examples/assets/1979423/32f27cc5-e91b-4cf3-9e02-416281391e7a">

**Comment by bkrem** [comment]
@chris13524 can you expand on when you're seeing this? Seems like when running locally. Did you follow the setup steps noted in each one e.g. https://github.com/WalletConnect/web-examples/tree/main/dapps/react-dapp-v2-with-ethers#running-locally and still run into this?

**Comment by chris13524** [comment]
Not sure if there is still an issue; but I don't care anymore. Closing
