### ISSUE TITLE
Wallet Connect doesn't process paymaster inputs

### ISSUE THREAD

**Issue by moneta** [WalletConnect/web-examples#232]
Describe the bug
I am using the wallet at https://react-web3wallet.vercel.app/walletconnect to test sending requests with Paymaster data to zkSync Era Mainnet/Testnet. However it fails.

Then I turn on the dev console on vercel.app and there is error: "insufficient funds for gas + value". Please refer to the attachment.

However, for zkSync Era transaction with paymaster parameters, it does not require the account to have ETH in order to send a transaction.

To Reproduce

Compose any transaction and put the paymaster params into it. For example
`{
    "from": "0x019bbe745b5c9b70060408Bf720B1E5172EEa5A3",
    "to": "0x1ab43093F4b3f8E5E4666d2062768ACCe67c9920",
    "gasLimit": "0x154d82",
    "value": 0,
    "data": "0xa9059cbb000000000000000000000000df6689e760aecb943c92271bc7dde5ef0648db170000000000000000000000000000000000000000000000000de0b6b3a7640000",
    "nonce": "0x77",
    "customData": {
        "gasPerPubdata": "0xc350",
        "paymasterParams": {
            "paymaster": "0xd4A49616cB954A2338ea1794C1EDa9d1254B23f0",
            "paymasterInput": "0x949431dc0000000000000000000000001ab43093f4b3f8e5e4666d2062768acce67c992000000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000"
        }
    },
    "maxFeePerGas": "0xee6b280",
    "maxPriorityFeePerGas": "0x00"
}`

The customData part is paymaster params.
Try to send this transaction and see error "insufficient funds for gas + value".

Expected behavior
A request message should be sent out successfully to zkSync Era Mainnet/Testnet.

Screenshots
See attachment
<img width="1129" alt="Screen Shot 2023-07-10 at 4 15 05 PM" src="https://github.com/WalletConnect/web-examples/assets/1636550/8f81f124-af91-4662-91db-b3a13d9cbf92">

**Comment by bkrem** [comment]
Hi @moneta,

WalletConnect as a protocol is agnostic towards any specific payload contents and does not do any validation there. This seems to be an error coming back from Ethers when the `sendTransaction fails`.
