### ISSUE TITLE
[Feature Request] - Sveltekit WalletConnect examples

### ISSUE THREAD

**Issue by Elliott-Green** [WalletConnect/web-examples#272]
Hi.

I love sveltekit and I love walletconnect.
I'd love to be able to use them together.
There's not a lot of examples that work out of the box without polyfills or hacks.

https://github.com/WalletConnect/walletconnect-monorepo/issues/864
https://github.com/search?q=%22ethers%22+%26%26+walletconnect++language%3Asvelte&type=code

**Comment by bkrem** [comment]
@glitch-txs looks like you covered this here: https://github.com/WalletConnect/web-examples/tree/main/dapps/web3modal/svelte

Should we close?
