### ISSUE TITLE
Local Development for React Wallet v2 has been Broken

### ISSUE THREAD

**Issue by kujtimprenkuSQA** [WalletConnect/web-examples#308]
# Description

Looks like this update https://github.com/WalletConnect/web-examples/pull/286 of the Next.js version has broken the local development of `wallets/react-wallet-v2`

![react-wallet-v2-next-issue](https://github.com/WalletConnect/web-examples/assets/95851345/8e39b434-42d6-466f-b2d6-e2abe055dd99)

OS: Windows 11, WSL
yarn version: 1.22.19
node version: 18.12.1

To confirm this you can `checkout` to any previous commit before the next.js update (https://github.com/WalletConnect/web-examples/pull/286) one e.g: https://github.com/WalletConnect/web-examples/commit/65f353ffd74b517b1adc6f373c305fb08d753d1b

```bash
git checkout 65f353ffd74b517b1adc6f373c305fb08d753d1b

cd wallets/react-wallet-v2

yarn && yarn dev 
# The app will run just fine.
```

**Comment by bkrem** [comment]
Thanks for making us aware @kujtimprenkuSQA 🙏 

Looks like an issue on the next.js side with specific versions of v12/v13. We've reverted for now since this is a nice to have.

Unclear why it passed on the renovatebot preview and then failed immediately on main.

**Comment by kujtimprenkuSQA** [comment]
> Thanks for making us aware @kujtimprenkuSQA 🙏
> 
> Looks like an issue on the next.js side with specific versions of v12/v13. We've reverted for now since this is a nice to have.
> 
> Unclear why it passed on the renovatebot preview and then failed immediately on main.

Thanks for the quick fix 👍 

This is unrelated to this issue but would you mind merging this one as it's just a line of code: https://github.com/WalletConnect/web-examples/pull/301 and maybe finding a reviewer for this other PR: https://github.com/WalletConnect/web-examples/pull/270

Thanks.
