### ISSUE TITLE
Add Web3Modal + Wagmi v2 example in React

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web-examples#420]
- We need to upgrade our React example from Wagmi v1 to[ Wagmi v2](https://wagmi.sh/react/getting-started). We already have an example with Next.

- This React example needs to be merged into this branch https://github.com/WalletConnect/web-examples/pull/419

**Comment by FaybianB** [comment]
Hello, may I be assigned this issue?

**Comment by Deepak2030** [comment]
Hey @glitch-txs can I work on this?

**Comment by dicethedev** [comment]
I just fixed this issue @glitch-txs you can check the PR - https://github.com/WalletConnect/web-examples/pull/421

**Comment by glitch-txs** [comment]
thanks guys!

@dicethedev this should be from branch [feat/wagmi-v2](https://github.com/WalletConnect/web-examples/pull/419)
because we have another folder under `web3modal/react`
you need to fork the repo with all branched, and move to the `feat/wagmi-v2` branch. 

Let me know if you it's ok

I'll prioritize you @Deepak2030 in the next contribution 🙏

**Comment by dicethedev** [comment]
Okay, @glitch-txs I will do that soon. Thanks for the feedback!
