### ISSUE TITLE
react-app.walletconnect.com Signature verification - Is it off spec?

### ISSUE THREAD

**Issue by SangameswaranRS** [WalletConnect/web-examples#5]
I just tried multiple libs with react-app.walletconnect.com and here are my issues.

1. For eth_sendTransaction and eth_signTransaction, the signature validity comes as true (Again it is just hardcoded as true there anyway)
2. For eth_personalSign and signing typed data, Is it off the actual spec ?
 For personal Sign I'm using Sign.signPrefixedMessage() and hex encoding the result with Numeric.toHexString. But still the "valid" flag is always set to false. I'm not sure if there are any discrepancies in implementation between web3j and web3js. The personal sign thing is working in the web3j vercel app (valid : true)
3. For signing typed data, the field EIP712Domain should be present according to the spec. But I don't see it. I'm observing this only recently and before that, the proper json was sent.

**Comment by SangameswaranRS** [comment]
PS: I'm writing my own wallet in kotlin, I'm using web3j/KEthereum.

**Comment by Seifollahy** [comment]
> I just tried multiple libs with react-app.walletconnect.com and here are my issues.
> 
> 1. For eth_sendTransaction and eth_signTransaction, the signature validity comes as true (Again it is just hardcoded as true there anyway)
> 2. For eth_personalSign and signing typed data, Is it off the actual spec ?
>  For personal Sign I'm using Sign.signPrefixedMessage() and hex encoding the result with Numeric.toHexString. But still the "valid" flag is always set to false. I'm not sure if there are any discrepancies in implementation between web3j and web3js. The personal sign thing is working in the web3j vercel app (valid : true)
> 3. For signing typed data, the field EIP712Domain should be present according to the spec. But I don't see it. I'm observing this only recently and before that, the proper json was sent.
> 
>

**Comment by SangameswaranRS** [comment]
Thanks @bkrem 

> The personal_sign and eth_sign examples in the dapp use ethers.utils.verifyMessage(…) and validate as expected with e.g. the example wallet (https://react-wallet.walletconnect.com/) or wallets that have already shipped v2 support (Steakwallet, Alphawallet).

For this, I made a mistake by not adding 0x prefix to the eth address sent. My bad here.

> You’re correct, this was initially missing in the example used, but we now use the exact example from the EIP712 spec:

I am implementing EIP 712 in JVM languages, but I am still facing some isses with respect to EIP712. Is there any JVM Example present for me to have a look at?

**Comment by SangameswaranRS** [comment]
@bkrem , for personal_sign I'm still seeing the same hardcoded hex that is being sent?
