### ISSUE TITLE
Sample Dapp is not authenticating with `projectId` parameter

### ISSUE THREAD

**Issue by arein** [WalletConnect/web-examples#50]
Repro steps: visit https://staging-rust.react-app.walletconnect.com/ and notice that the websocket doesn't connect

The connection string lacks a project Id. Example:

```
wss://staging.rust-relay.walletconnect.com/?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtuazZ3NlgzQ0dQUFJFNDhyMlBmWldZUzN3NkM2cFh4b3BQa2JmQjkxR0sycSIsInN1YiI6ImQxMmZhOTA3OTZlNzcyMDU1YTA3YmI4ZTk0OTRjNzJjOTQ1ZDcyMTdlNTUwODY2MzdkMzg3YmMwMWY5MWM0YmYiLCJhdWQiOiJ3c3M6Ly9zdGFnaW5nLnJ1c3QtcmVsYXkud2FsbGV0Y29ubmVjdC5jb20iLCJpYXQiOjE2NjE5ODUzMTUsImV4cCI6MTY2MjA3MTcxNX0.jjs7zDn4GnUOb0giw3ymAaO6PrdG5n-ZgA1MvToJkNJgsbmMh7EdZlRYUkv4brH7URhVhuxoWfLemVdpvbANCw&ua=wc-2%2Fjs-2.0.0-rc.1%2Fmacos-chrome-104.0.0%2Fbrowser%3Astaging-rust.react-app.walletconnect.com
```

This works on the [example wallet](https://staging-rust.react-wallet.walletconnect.com/).

**Comment by bkrem** [comment]
Fixed here and merged into the `config/staging-rust-relay` branch: https://github.com/WalletConnect/web-examples/commit/8db9560b724d40e144d60dce5d3dbfd64372475d
