### ISSUE TITLE
NEXT_PUBLIC_PIMLICO_KEY

### ISSUE THREAD

**Issue by xiao0502** [WalletConnect/web-examples#509]
What does NEXT_PUBLIC_PIMLICO_KEY mean? Where to get it?

**Comment by lukaisailovic** [comment]
Hi @xiao0502,
Pimlico was used to sponsor UserOps for smart accounts that were implemented in our `rect-wallet`. Latest changes that are pushed today made that parameter optional, same as `NEXT_PUBLIC_ZERODEV_PROJECT_ID`. If you wish to enable smart accounts, you can do so in the settings tab. Enabling them will require you to provide the mentioned environment variables.

Please let us know if you encounter any additional issues.
