### ISSUE TITLE
Sunset `rust-relay` Sample Apps

### ISSUE THREAD

**Issue by arein** [WalletConnect/web-examples#54]
* `https://staging-rust.react-wallet.walletconnect.com/` 
* `https://staging-rust.react-app.walletconnect.com/`

Can be remove as we sunsetted `ts relay` in favor of `rs relay`.

**Comment by bkrem** [comment]
- [x] Removed from Cloudflare DNS
- [x] Removed from Vercel > Domains config
- [x] Cleaned up in Vercel > Environment variables
- [x] Cleaned up `config/staging-rust-relay` branch in this repo
