### ISSUE TITLE
Unable to style the connect button in the Svelte web example

### ISSUE THREAD

**Issue by 612crypto** [WalletConnect/web-examples#587]
I am using the [Svelte web example](https://github.com/WalletConnect/web-examples/tree/main/dapps/web3modal/svelte) as a starting point. I am trying to style the connect button, but I can't seem to figure it out.

I tried using the `themeVariables` option [found here](https://docs.walletconnect.com/advanced/walletconnectmodal/theming). I added this to the code in `/src/lib/web3modal.ts`, but it doesn't seem to have any effect (the button remains the default blue).

```
createWeb3Modal({
    wagmiConfig,
    projectId,
    themeMode: 'dark',
    themeVariables: {
        '--wcm-font-family': 'Roboto, sans-serif',
        '--wcm-accent-color': '#FFD700'
    }
    featuredWalletIds: [],
    enableAnalytics: true,
    customWallets
})
```

Any ideas?

**Comment by glitch-txs** [comment]
This is an issue in the Web3Modal SDK, please open an issue [there](https://github.com/WalletConnect/web3modal)
