### ISSUE TITLE
request: add example for react/siwe and server api

### ISSUE THREAD

**Issue by aquariuslt** [WalletConnect/web-examples#591]
- type: example code require

Hi, could you please provide an example of [(SIWE) one-click auth](https://docs.walletconnect.com/appkit/react/core/siwe) using React on the frontend and any server-side API (e.g., Node.js with Express) on the backend? A guide demonstrating this integration would be very helpful.

**Comment by aquariuslt** [comment]
close since have integerated

**Comment by glitch-txs** [comment]
will open as it's something we want to add here. Also feel free to open a PR 🙏

**Comment by aquariuslt** [comment]
> close since have integerated

I have make a minimal repository as example.
https://github.com/aquariuslt/w3m-oneclick-siew-example

**Comment by rtomas** [comment]
https://github.com/WalletConnect/web-examples/tree/main/dapps/appkit-siwe/react
