### ISSUE TITLE
console show too many

### ISSUE THREAD

**Issue by leeliplus** [WalletConnect/web-examples#679]
when i run demo  https://react-wallet.walletconnect.com/walletconnect
there are too many repeat console，can this fix ?

![console](https://github.com/user-attachments/assets/f070b6c0-d947-459b-8854-e64abe8f0fda)
![console2](https://github.com/user-attachments/assets/d32ad2ca-bc03-4be1-a16e-f689ee496d1c)

**Comment by kundanlmr** [comment]
same issues i am also facing or in my network tab this api calling many times 
https://rpc.walletconnect.com/v1/?chainId=0:0&projectId=000000 or wallet got automatically disconnect if i reload the page plz help me

**Comment by glitch-txs** [comment]
@leeliplus this is intended. 

@kundanlmr please open another issue in the right repository
