### ISSUE TITLE
[dapps] Replace legacy modal with Web3Modal v2 in standalone mode

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/web-examples#74]
See: https://github.com/WalletConnect/web3modal/tree/V2/examples/react-standalone

Replaced in:
- [x] react-dapp-v2 - https://github.com/WalletConnect/web-examples/commit/99ef432c76ff211e45c0e17c2b8d75c3aed7fb1d
- [x] react-dapp-auth - #79 
- [x] react-dapp-v2-with-ethers
- [x] react-dapp-v2-with-web3js

**Comment by chadyj** [comment]
Yasssssss

**Comment by bkrem** [comment]
Requires: https://github.com/WalletConnect/web3modal/pull/691
