### ISSUE TITLE
Websocket connection to 'wss://relay.walletconnect.com/?auth=eyJhbGciOiJFZERTQSIsI...' failed

### ISSUE THREAD

**Issue by qylixin** [WalletConnect/web-examples#85]
hi all:

I registered an account on the "cloud.walletconnect.com" website and got a projectID, when I test the "react-dapp-v2-with-ethers" project on localhost, after configuring the correct projectID, everything works fine , but when I deployed the project to a linux server, it failed to run. The error message is "Websocket connection to 'wss://relay.walletconnect.com/?auth=eyJhbGciOiJFZERTQSIsI...' failed", the domain name and projectID configuration of the linux server are all correct, what may be the cause of this problem, and how solve?

**Comment by crypblizz8** [comment]
hey @qylixin, could you provide the snippet for the whole error message + also try to go into Cloud and reset your ID + add your Linux domain to the allowList to see if that works?

**Comment by norld** [comment]
i got same error

**Comment by norld** [comment]
when i using my mac that running smothly but when publish to server got this error

**Comment by norld** [comment]
Core Initilization Failure at epoch 1669892018389

**Comment by chadyj** [comment]
@qylixin It looks like you are within China? If so, can you please try `relay.walletconnect.org` as an alternative relay.

**Comment by 0xtsukino** [comment]
@qylixin i was running into similar issue in production, and was able to fix it by updating the url of my project to includes the protocol as well. For example, if you domain is `www.hello.com`, try updating you project to include `https://www.hello.com` and `https://hello.com`

**Comment by qylixin** [comment]
I used @chadyj  and @0xtsukino's  method and it works now，thanks!
