### ISSUE TITLE
react-dapp-v2 example does not connect to Metamask Mobile

### ISSUE THREAD

**Issue by 0xtsukino** [WalletConnect/web-examples#90]
How to reproduce error:
1. On a mobile device (android or ios) with metamask installed, go to [react-dapp-v2-with-ethers](https://react-dapp-v2-with-ethers.vercel.app/) or [react-dapp-v2-with-web3js](https://react-dapp-v2-with-web3js.vercel.app/)
2. Click connect, and then open with Metamask
3. Observe that no connection request prompted in metamask

You can also try the steps above but with Trust wallet, and see that the connection request is prompted once Trust is opened.

Would love to see if anyone has ran into the same issue and has found a fix.

**Comment by chadyj** [comment]
Metamask Mobile doesn't yet support v2.
